### ISSUE TITLE
Unable to import more than 10,000 links in Bit.ly

### ISSUE THREAD

**Issue by jschroed91** [shlinkio/shlink-importer#18]
The bitly API for retrieving bitlinks of a group has a bit of an odd behavior that I haven't been able to find documentation on.

There seems to be a max value on the `page` query param of `100`, although there's no error when requesting beyond page 100.

On page 100, the response pagination metadata includes the `next` link properly with `page=101`, however when hitting that endpoint for page 101, it returns no links, and pagination metadata has total = 0, and `next` is not set.

In this importer script, once it reaches page 101, it thinks it's done importing links because there's no `next` in the pagination now, so it ends the process and does not provide a "continue token".

Seems like we'd need to add some ugly custom logic to reset the page counter back to 0 and set the created_before value to the last link's created_at from page 100, so that the import continues. Alternatively, could generate a continue token on page 100 and show that.

Since max limit is 100, and max page is 100, we can only import 10,000 links at a time, and I've been having to manually create the continue token for the next batch based on the last link that was inserted.

I am migrating 1M+ links, so doing it in batches of 10,000 at a time and having to manually find and generate the continue token ended up being far too tedious -- instead I ended up writing a separate script to populate the DB unfortunately.

**Comment by acelaya** [comment]
Wow, that's odd. Also, amazing job reverse engineering how the logic works. I'm impressed.

I'll try to work around this thing using some of the proposals. I may need helpt, though, as I don't have access to a bitly account with that many links.

**Comment by jschroed91** [comment]
Thanks! Unfortunately our bitly contract expires in 2 days so I won't have access to it beyond that point, but I can certainly help in code review / testing with a mock API since I do at least have all of the data for enough links.

Sidenote: Great work overall on shlink, we are migrating away from Bitly that we've been using for about 6+ years to a self-hosted option, which will save us quite a bit on costs :) Shlink seems like the golden ticket for us after some research around - the modern architecture and deployment capabilities (docker) were big winners in our book.
