### ISSUE TITLE
Can we import links from Bitly with existing stats?

### ISSUE THREAD

**Issue by brownsugar** [shlinkio/shlink-importer#20]
We can get some useful stats of Bitly links like click count, date history or country stats by their API, will such features available in the importer in the future?
Or, does shlink has plan to create some API to let users edit the stats of short links?

**Comment by acelaya** [comment]
The intention is to, eventually, support importing stats as well.

**Comment by brownsugar** [comment]
Hi @acelaya, I'm going to migrate the links from Bitly to Shlink, but I'm concerned that if the importer supports importing link stats later, am I able to sync the clicks count?
For example, I imported a Bitly link with 10 clicks to Shlink, then it got 5 clicks at Shlink, when the stats import feature is available, I synced the stats, will the clicks in Shlink become 15?

**Comment by acelaya** [comment]
That's a question hard to answer. Ideally stats will be merged, so it would be 15, but I haven't looked into this yet, so I can't confirm what dificulties am I going to face.

Also, this is not a priority at the moment, which means at least a couple of months will pass until this feature is supported.

**Comment by brownsugar** [comment]
Got it, thanks for the updates.
I think if we can customize the link clicks, this would be easier.
