### ISSUE TITLE
[QUESTION] import to existing Shlink installation with Links

### ISSUE THREAD

**Issue by MartinHotmann** [shlinkio/shlink-importer#29]
Hy @acelaya just quickly wanted to ask if this importer satisfies my needs for this case?

1. Shlink 1: `demo1.domain.tld` (30 Links)
2. Shlink 2: `demo2.domain.tld` (190 Links)

Now I would like to migrate (import) Shlink1-Installation into Shlink2-Installation. Does this work, if both installations already has links/entries in it?

Also: does this alter (move) the links so they are not available to Shlink1 anymore and therefore just redirects to Shlink2 or what happens to the old links?

Assume I have a Link:
`demo1.domain.tld/testShlinkLink`

And migrate this to Shlink2

Will this also redirect the URL `demo1.domain.tld/testShlinkLink` at the Shlink1 applicatin to `demo2.domain.tld/testShlinkLink` so I do not have to rewrite/edit all Links? or does it at least generate me a `.htaccess` file which I then can place at the rootfolder of Shlink1 Application so this will redirect ALL of these "imported" Shlinks to the new Shlink destination/application?

**Comment by acelaya** [comment]
> Now I would like to migrate (import) Shlink1-Installation into Shlink2-Installation. Does this work, if both installations already has links/entries in it?

Yes. It will take the 30 links from Shlink 1, together with their visits, and import them to Shlink 2, ending with 220 links in the second instance.

> Also: does this alter (move) the links so they are not available to Shlink1 anymore and therefore just redirects to Shlink2 or what happens to the old links?

No, this tool just imports data, simplifying hosting or database migrations (in the case of importing from another Shlink instance), but it's up to you to decide which Shlink instances are available and resolved by the DNS.

The original instance remeains unaltered, and used just as the source of data.

Also, take into consideration that importing from another Shlink instance is still under development and won't be supported until Shlink 2.7.0 is released. See https://github.com/shlinkio/shlink/issues/1066
