### ISSUE TITLE
Handle errors when loading visits from another Shlink instance

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-importer#33]
Currently, if an exception is thrown when loading visits for a short URL, the whole import process fails.

Instead, it should only fail to import the visits with a warning, and continue with the process.

**Comment by loelkes** [comment]
In the related issue I was using the import feature for migration and I found it very helpful that the entire process failed and no URL was imported. It would be nice to have the option to choose what happens if an import fails.

**Comment by acelaya** [comment]
Sure!

In any case, what Shlink already does is keep track of what URLs have already been imported, and skip them if you try to import again from the same source, which means a second run would not duplicate any data.

Same with visits.
