### ISSUE TITLE
using with Docker

### ISSUE THREAD

**Issue by cirrusflyer** [shlinkio/shlink-importer#52]
Can this be used for a Shlink Docker installation as the target?  Source is a Shlink dist file version.

**Comment by acelaya** [comment]
Yes, you can import from any Shlink instance to any Shlink instance.

**Comment by cirrusflyer** [comment]
I've read the steps, but can you elaborate on how to use this tool in Docker?

**Comment by acelaya** [comment]
Here https://shlink.io/documentation/install-docker-image/#usage

See the `Interact with Shlink's CLI on a running container.` part.
